query BLogListGQL($page: Int!) {
	blogList(page: $page) {
		maxpage
		blogList {
            title
            vote
            view
			user{
				displayName
				gravataremail
			}
			slug
			createTime
		}
	}
}
