# Generated by Django 2.0.4 on 2018-04-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=64)),
                ('judge_status', models.CharField(max_length=256)),
            ],
        ),
    ]
