# Generated by Django 2.0.4 on 2018-05-01 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgeinfo',
            fields=[
                ('judgeinfo_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('result', models.CharField(default='', max_length=64)),
                ('time_cost', models.CharField(max_length=12)),
                ('memory_cost', models.CharField(max_length=12)),
                ('additional_info', models.CharField(max_length=512)),
                ('case', models.SmallIntegerField(db_index=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=64)),
                ('judge_status', models.CharField(max_length=64)),
                ('code', models.CharField(blank=True, max_length=65535)),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Submit time')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_id'],
                'permissions': (('view_all', 'Can view all submission'),),
            },
        ),
        migrations.AddField(
            model_name='judgeinfo',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Submission'),
        ),
    ]
