# Generated by Django 2.0.4 on 2018-04-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.CharField(blank=True, max_length=65535),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='submission',
            name='judge_status',
            field=models.CharField(max_length=64),
        ),
    ]
