# Generated by Django 2.0.4 on 2018-05-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='judge_status',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
