# Generated by Django 2.0.4 on 2018-04-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeinfo',
            name='case',
            field=models.SmallIntegerField(db_index=True, default=0, unique=True),
        ),
    ]
