# Generated by Django 2.0.4 on 2018-04-21 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0002_auto_20180421_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submit_time',
            field=models.DateTimeField(null=True, verbose_name='Submit time'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
