# Generated by Django 2.0.4 on 2018-04-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20180430_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgeinfo',
            old_name='memorycost',
            new_name='memory_cost',
        ),
        migrations.RenameField(
            model_name='judgeinfo',
            old_name='timecost',
            new_name='time_cost',
        ),
    ]
