# Generated by Django 2.0.4 on 2018-04-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20180430_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeinfo',
            name='case',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
    ]
