# Generated by Django 2.0.4 on 2018-04-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20180430_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgeinfo',
            old_name='addition_info',
            new_name='additional_info',
        ),
    ]
