# Generated by Django 2.0.4 on 2018-04-21 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20180421_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Submit time'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
