# Generated by Django 2.0.4 on 2018-04-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20180430_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeinfo',
            name='case',
            field=models.SmallIntegerField(db_index=True, editable=False, null=True),
        ),
    ]
