query ProblemDetailGQL($slug: String!) {
	problem(slug: $slug) {
		problemId
		title
		content
		standardInput
		standardOutput
		constraints
		resource
		note
		timeLimit
		memoryLimit
		sampleSet {
			inputContent
			outputContent
		}
		visible
		discussionvisible
	}
}
