mutation RegisterGQL(
	$username: String!
	$password: String!
	$email: String!
	$displayName: String!
	$school: String
	$company: String
	$location: String
) {
	register(
		username: $username
		password: $password
		email: $email
		displayName: $displayName
		school: $school
		company: $company
		location: $location
	) {
		token
		payload
		permission
		user{
			displayName
			gravataremail
			school
			company
			location
			about
			group
		}
	}
}
