mutation UserLogin($username: String!, $password: String!) {
	UserLogin(username: $username, password: $password) {
		token
	}
}

mutation verifyToken($token: String!) {
	verifyToken(token: $token) {
		payload
	}
}
