mutation UserLogin($username: String!, $password: String!) {
	userLogin(username: $username, password: $password) {
		token
		payload
	}
}

mutation VerifyToken($token: String!) {
	verifyToken(token: $token) {
		payload
	}
}

mutation RefreshToken($token: String!) {
	refreshToken(token: $token) {
		token
		payload
	}
}
