query SubmissionListGQL($page: Int!) {
	submissionList(page: $page) {
		maxpage
		submissionList {
            submissionId
            submitTime
            user
			problem
            judgeStatus
            language
		}
	}
}
