query SubmissionListGQL($page: Int!,$date: String!) {
	submissionList(page: $page,date: $date) {
		maxpage
		submissionList {
            submissionId
			failedCase
            submitTime
            user
			userGravataremail
			problem
            judgeStatus
            language
			color
			timeCost
			memoryCost
		}
	}
}
