query SubmissionListGQL(
	$page: Int!
	$date: String!
	$pk: ID
	$user: String
	$problem: String
	$judgeStatus: String
	$language: String
) {
	submissionList(
		page: $page
		date: $date
		pk: $pk
		user: $user
		problem: $problem
		judgeStatus: $judgeStatus
		language: $language
	) {
		maxpage
		submissionList {
			submissionId
			failedCase
			submitTime
			user {
				gravataremail
				displayName
			}
			problem {
				title
			}
			judgeStatus
			language
			color
			timeCost
			memoryCost
		}
	}
}
