# Generated by Django 2.0.4 on 2018-05-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, default='Default Title', max_length=256)),
                ('content', models.TextField(blank=True)),
                ('standard_input', models.TextField(blank=True)),
                ('standard_output', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('sample_explanation', models.TextField(blank=True, max_length=1024)),
                ('resource', models.CharField(blank=True, max_length=256)),
                ('time_limit', models.PositiveIntegerField(default=2000)),
                ('memory_limit', models.PositiveIntegerField(default=128)),
                ('solved_number', models.PositiveIntegerField(default=0, editable=False)),
                ('try_number', models.PositiveIntegerField(default=0, editable=False)),
                ('checker', models.CharField(default='wcmp', max_length=256)),
                ('visible', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['problem_id'],
                'permissions': (('download_problem_data', 'Can download test data'),),
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('input_content', models.CharField(max_length=512, null=True)),
                ('output_content', models.CharField(max_length=512, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
            ],
        ),
    ]
