# Generated by Django 2.0.4 on 2018-04-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
