# Generated by Django 2.0.4 on 2018-04-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='memoryLimit',
            new_name='memory_limit',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problemId',
            new_name='problem_id',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='sampleExplanation',
            new_name='sample_explanation',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='sampleInput',
            new_name='sample_input',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='sampleOutput',
            new_name='sample_output',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='solvedNumber',
            new_name='solved_number',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='specialJudge',
            new_name='special_judge',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='standardInput',
            new_name='standard_input',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='timeLimit',
            new_name='time_limit',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='tryNumber',
            new_name='try_number',
        ),
    ]
