# Generated by Django 2.0.4 on 2018-05-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='sample_explanation',
        ),
    ]
