# Generated by Django 2.0.4 on 2018-04-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20180413_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='standardOutput',
            new_name='standard_output',
        ),
    ]
