# Generated by Django 2.0.4 on 2018-05-10 13:13

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_remove_problem_sample_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='constraints',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='standard_input',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='standard_output',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
