# Generated by Django 2.0.4 on 2018-04-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20180430_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_explanation',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='problem',
            name='special_judge',
            field=models.CharField(default='wcmp', max_length=256),
        ),
        migrations.AlterField(
            model_name='problem',
            name='standard_input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='standard_output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='input_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='output_content',
            field=models.TextField(null=True),
        ),
    ]
