# Generated by Django 2.0.4 on 2018-04-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20180430_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='special_judge',
            new_name='checker',
        ),
    ]
