# Generated by Django 2.0.4 on 2018-04-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20180414_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.CharField(default='[]', max_length=1024),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.CharField(default='[]', max_length=1024),
        ),
    ]
