# Generated by Django 2.0.4 on 2018-04-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20180430_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['problem_id'], 'permissions': (('download_data', 'Can download test data'),)},
        ),
    ]
