# Generated by Django 2.0.4 on 2018-04-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20180423_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('input_content', models.CharField(max_length=256)),
                ('output_content', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_output',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='standard_input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='standard_output',
        ),
        migrations.AddField(
            model_name='sample',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
