# Generated by Django 2.0.4 on 2018-04-27 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20180427_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='submission',
            new_name='problem',
        ),
        migrations.AlterField(
            model_name='sample',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
