# Generated by Django 2.0.4 on 2018-04-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180413_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='displayName',
            new_name='display_name',
        ),
    ]
