# Generated by Django 2.0.4 on 2018-05-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180507_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='about',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
