query UserListGQL($page: Int!, $filter: String) {
	userList(page: $page, filter: $filter) {
		maxpage
		userList {
			username
			gravataremail
			displayName
			school
			company
			location
			about
		}
	}
}
