query ProfileGQL($username: String!) {
	user( username: $username){
		heatmap
		analysis
		displayName
		gravataremail
		group
		school
		company
		location
		about
		solved
		tried
		joinedDate
		lastloginDate
		rank
		submissionStatistics{
			AC
			TLE
			CE
			WA
			RE
			OLE
			MLE
		}
	}
}
