query ProfileGQL($username: String!) {
	user( username: $username){
		heatmap
		analysis
		displayName
		gravataremail
		group
		school
		company
		location
		about
		solved
		tried
		joinedDate
		lastloginDate
		rank
		submissionStatistics{
			ac
			tle
			ce
			wa
			re
			ole
			mle
		}
	}
}
