query UserProfileGQL{
	user{
        displayName,
        school,
        company,
        location,
        about,
        group,
	}
}

mutation UserInfoUpdateGQL( $company: String! , $displayName: String! , $about: String! , $school: String!, $location: String!){
        UserInfoUpdate( company: $company , displayName: $displayName , about: $about , school: $school, location: $location){
                state
        }
}